version: "3"

services:
  db:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  cache:
    container_name: redis
    image: redis:7.2.2-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: redis-server --save 10 1
    volumes: 
      - cache-data:/data

  api:
    container_name: axum
    build: 
      context: ./server
    volumes:
      - ./server:/usr/src/app
    # network_mode: host
    # environment:
    #   - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
    #   - REDIS_URL=redis://localhost/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://cache/
    command: bash -c "sqlx migrate run && cargo run"
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_started

volumes:
  db-data:
  cache-data: