version: "3"

services:
  db:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  cache:
    container_name: redis
    image: redis:7.2.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 10 1
    volumes: 
      - cache-data:/data

volumes:
  db-data:
  cache-data: